spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tax_application?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
